config/routes.rb
Rails.application.routes.draw do
  resources :order_requests

  devise_for :users, controllers: { registrations: "users/registrations" }
  root 'pages#index'

  resources :orders
  resources :customers
  resources :drivers
  resources :vehicles
  resources :products

  # pages
  get "/faq", to: "pages#faq"
  get "/about", to: "pages#about"
  get "/decisions_for_business", to: "pages#decisions_for_business"

end

app/models/order.rb
class Order < ApplicationRecord
  STATUSES = ["Pending", "In progress", "Completed", "Canceled"]

  validates :customer, presence: true
  validates :product, presence: true
  validates :driver, presence: true
  validates :quantity, presence: true
  validates :status, presence: true, inclusion: { in: STATUSES, message: "%{value} is not a valid status." }

  validate :validate_quantity

  belongs_to :customer
  belongs_to :product
  belongs_to :driver

  after_commit :set_tracking_number, :on => :create
  after_commit :set_status, :on => :create

  before_create :decrease_product_available_quantity
  before_create :formatted_created_at

  before_update :prevent_update, if: :status_is_in_progress?
  before_update :handle_quantity_change, if: :quantity_changed?

  before_save :set_total_price

  before_destroy :prevent_destroy, if: :status_is_in_progress?
  before_destroy :return_quantity_to_product, if: :status_is_in_canceled?

  def formatted_created_at
    created_at.in_time_zone("Europe/Kyiv").strftime("%d.%m.%Y %H:%M")
  end

  private

  def decrease_product_available_quantity
    product.update(available_quantity: product.available_quantity - self.quantity)
  end

  def set_total_price
    self.total_price = product.unit_price * self.quantity
  end

  def set_tracking_number
    update_column(:tracking_number, generate_tracking_number)
  end

  def set_status
    update_column(:status, STATUSES.first.to_s)
  end

  def generate_tracking_number
    "MDN#{self.id.to_s.rjust(6, '0')}"
  end

  def status_is_in_progress?
    true if self.status == "In progress"
  end

  def status_is_in_canceled?
    true if self.status == "Canceled"
  end

  def prevent_update
    errors.add(:status, "Can't update info while order is in progress.")
    throw(:abort)
  end

  def prevent_destroy
    errors.add(:status, "Can't destroy while order is in progress.")
    throw(:abort)
  end

  def return_quantity_to_product
    product.update(available_quantity: product.available_quantity + self.quantity)
  end

  def handle_quantity_change
    product.update(available_quantity: product.available_quantity + self.quantity_was - self.quantity)
  end

  def validate_quantity
    if self.quantity <= 0
      errors.add(:quantity, "Quantity must be greater than 0.")
    elsif self.quantity > product.available_quantity
      errors.add(:quantity, "Quantity can't be greater than available quantity. #{product.available_quantity} units of #{product.name.downcase} left in stock.")
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  def index
    @orders = Order.all
  end

  def new
    @order = Order.new
  end

  def edit
  end

  def create
    @order = Order.new(order_params)
    if @order.save
      redirect_to orders_path
    else
      render :new
    end
  end

  def update
    if @order.update order_params
      redirect_to orders_path
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    redirect_to orders_path if @order.destroy
  end

  private

  def set_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:tracking_number, :product_id, :customer_id, :driver_id, :quantity, :total_price, :status)
  end
end

app/views/orders/edit.html.erb
<% content_for :title do %>
  Edit Order
<% end %>

<section class="entity-table">
  <h1 class="mb-3">Editing Order <%= @order.tracking_number %></h1>
  <%= form_with model: @order, url: order_path do |form| %>
    <div class="table-container">
      <table class="table-bordered">
        <thead>
        <tr>
          <th>Tracking Number</th>
          <th>Called At</th>
          <th>Customer</th>
          <th>Driver</th>
          <th>Vehicle</th>
          <th>Product</th>
          <th>Quantity</th>
          <th>Price</th>
          <th>Address</th>
          <th>Status</th>
          <th></th>
        </tr>
        </thead>

        <tbody>
        <tr>
          <td><%= @order.tracking_number %></td>
          <td><%= @order.formatted_created_at %></td>
          <td><%= link_to "#{@order.customer.name + " " + @order.customer.surname}", customer_path(@order.customer_id), class: "link-opacity-100-hover" %></td>
          <td><%= link_to "#{@order.driver.name + " " + @order.driver.surname}", driver_path(@order.driver_id), class: "link-opacity-100-hover" %></td>
          <td><%= link_to "#{@order.driver.vehicle.brand + " " + @order.driver.vehicle.model}", vehicle_path(@order.driver.vehicle_id), class: "link-opacity-100-hover" %></td>
          <td><%= link_to "#{@order.product.name}", product_path(@order.product_id), class: "link-opacity-100-hover" %></td>
          <td>
            <% if @order.status == "Pending" %>
              <%= form.text_field :quantity %>
            <% else %>
              <%= @order.quantity %>
            <% end %>
          </td>
          <td>$<%= @order.total_price %></td>
          <td><%= @order.customer.address %></td>
          <td><%= form.select :status, ["Pending", "In progress", "Completed", "Canceled"], selected: @order.status %></td>
          <td>
            <div class="action-container">
              <%= link_to "Back", order_path(@order), class: "btn btn-primary back-button" %>
              <%= form.submit "Save", class: "btn btn-success" %>
            </div>
          </td>
        </tr>
        </tbody>
      </table>
    </div>
  <% end %>
</section>

app/views/orders/index.html.erb
<% content_for :title do %>
	Orders
<% end %>

<section class="entity-table">
	<h1 class="mb-3">Orders</h1>

	<div class="table-container">
		<table class="table-bordered">
			<thead>
			<tr>
				<th>Tracking Number</th>
				<th>Called At</th>
				<th>Customer</th>
				<th>Driver</th>
				<th>Vehicle</th>
				<th>Product</th>
				<th>Quantity</th>
				<th>Price</th>
				<th>Address</th>
				<th>Status</th>
				<th></th>
			</tr>
			</thead>
			<% @orders.each do |order| %>
				<tbody>
					<tr>
						<td><%= order.tracking_number %></td>
						<td><%= order.formatted_created_at %></td>
						<td><%= link_to "#{order.customer.name + " " + order.customer.surname}", customer_path(order.customer_id), class: "link-opacity-100-hover" %></td>
						<td><%= link_to "#{order.driver.name + " " + order.driver.surname}", driver_path(order.driver_id), class: "link-opacity-100-hover" %></td>
						<td><%= link_to "#{order.driver.vehicle.brand + " " + order.driver.vehicle.model}", vehicle_path(order.driver.vehicle_id), class: "link-opacity-100-hover" %></td>
						<td><%= link_to "#{order.product.name}", product_path(order.product_id), class: "link-opacity-100-hover" %></td>
						<td><%= order.quantity %></td>
						<td>$<%= order.total_price %></td>
						<td><%= order.customer.address %></td>
						<td><%= order.status %></td>
						<td>
							<div class="action-container">
								<%= link_to "Show", order_path(order), class: "btn btn-primary show-button" %>
								<%= button_to "Delete", order, method: :delete, class: "btn btn-danger delete-button" %>
							</div>
						</td>
					</tr>
				</tbody>
			<% end %>
		</table>
	</div>
</section>

app/views/orders/show.html.erb
<% content_for :title do %>
  Order
<% end %>

<section class="entity-table">
  <h1 class="mb-3">Order <%= @order.tracking_number %></h1>

  <div class="table-container">
    <table class="table-bordered">
      <thead>
      <tr>
        <th>Tracking Number</th>
        <th>Called At</th>
        <th>Customer</th>
        <th>Driver</th>
        <th>Vehicle</th>
        <th>Product</th>
        <th>Quantity</th>
        <th>Price</th>
        <th>Address</th>
        <th>Status</th>
        <th></th>
      </tr>
      </thead>
        <tbody>
        <tr>
          <td><%= @order.tracking_number %></td>
          <td><%= @order.formatted_created_at %></td>
          <td> <%= link_to "#{@order.customer.name + " " + @order.customer.surname}", customer_path(@order.customer_id), class: "link-opacity-100-hover" %></td>
          <td><%= link_to "#{@order.driver.name + " " + @order.driver.surname}", driver_path(@order.driver_id), class: "link-opacity-100-hover" %></td>
          <td><%= link_to "#{@order.driver.vehicle.brand + " " + @order.driver.vehicle.model}", vehicle_path(@order.driver.vehicle_id), class: "link-opacity-100-hover" %></td>
          <td><%= link_to "#{@order.product.name}", product_path(@order.product_id), class: "link-opacity-100-hover" %></td>
          <td><%= @order.quantity %></td>
          <td>$<%= @order.total_price %></td>
          <td><%= @order.customer.address %></td>
          <td><%= @order.status %></td>
          <td>
          <td>
            <div class="action-container">
              <%= link_to "Back", orders_path, class: "btn btn-primary" %>
              <%= link_to "Edit", edit_order_path(@order), class: "btn btn-primary" %>
            </div>
          </td>
        </tr>
        </tbody>
    </table>
  </div>
</section>