config/routes.rb
Rails.application.routes.draw do
  resources :order_requests

  devise_for :users, controllers: { registrations: "users/registrations" }
  root 'pages#index'

  resources :orders
  resources :customers
  resources :drivers
  resources :vehicles
  resources :products

  # pages
  get "/faq", to: "pages#faq"
  get "/about", to: "pages#about"
  get "/decisions_for_business", to: "pages#decisions_for_business"

end

app/views/pages/about.html.erb
<% content_for :title do %>
  About Us
<% end %>
<section class="article__section">
  <h1>About Us</h1>

  <p>
    At MAKE Delivery, logistics isn’t just our job—it’s our passion. We’ve built a reputation for transforming complex shipping needs into straightforward, reliable solutions, helping businesses of all sizes to reach their goals. Our mission is to create seamless and efficient delivery experiences, from the first mile to the last. With MAKE Delivery, you gain more than a service provider; you gain a committed partner who values your business’s success as much as you do. From urgent, time-sensitive deliveries to large-scale shipping projects, we’re here to make sure your products arrive safely and on time.
  </p>

  <p>
    We believe that every delivery has the potential to make a positive impact, which is why we prioritize quality and accountability in everything we do. Our team of logistics experts is driven by a dedication to excellence, combining cutting-edge technology with a human touch to keep you informed and in control every step of the way. MAKE Delivery adapts to your unique needs, whether it’s optimizing routes, ensuring secure handling, or providing real-time tracking updates. Each service we offer is designed with precision, crafted to align with your business’s goals, and dedicated to keeping your supply chain moving smoothly.
  </p>

  <p>
    At MAKE Delivery, we’re proud to be more than just another logistics company. We’re a trusted partner, here to support you as your business grows, meeting today’s challenges and preparing for tomorrow’s opportunities. We understand that your success depends on efficient, reliable, and scalable logistics solutions, and we’re here to deliver just that. With MAKE Delivery, you can have peace of mind knowing that your shipments are in the best possible hands. Where your needs meet our expertise — MAKE Delivery.
  </p>
</section>

app/views/pages/decisions_for_business.html.erb
<% content_tag :title do %>
  Decisions for business
<% end %>

<section class="article__section">

  <h1>Decisions for business</h1>

  <p>
    MAKE Delivery offers a suite of business solutions designed to optimize every aspect of your logistics process. We understand that each business has unique needs, and we’re here to provide flexible, scalable options that help you streamline operations and increase efficiency. From small startups to large enterprises, our goal is to tailor our services to meet your specific requirements, ensuring that every shipment is handled with care and professionalism. With MAKE Delivery, you’ll experience logistics that evolve with your business, supporting you through each phase of growth.
  </p>

  <p>
    Our business solutions include customized supply chain management, expedited shipping options, and industry-specific solutions for sectors like e-commerce, manufacturing, and retail. Our advanced tracking systems offer real-time visibility into your shipments, so you’re always in the loop. Additionally, our data-driven analytics tools allow you to gain valuable insights into your logistics performance, helping you make informed decisions to optimize cost and efficiency. At MAKE Delivery, we go beyond standard shipping to offer integrated solutions that truly work for your business.
  </p>

  <p>
    Partnering with MAKE Delivery means partnering with a team committed to innovation and customer satisfaction. We’re here to help you overcome logistical challenges, adapt to market demands, and achieve seamless operations. With our expertise and support, you’ll gain more than just delivery services; you’ll gain a strategic advantage that enables you to focus on what matters most—growing your business. Discover the difference our tailored solutions can make and experience logistics built around your success.
  </p>

</section>

app/views/pages/faq.html.erb
<% content_for :title do %>
	FAQ
<% end %>

<section class="article__section">
	<h1 class="faq__first-heading">Frequently Asked Questions</h1>

	<h2 class="faq__second-heading">What does your company offer?</h2>
	<p class="faq__paragraph">Our logistics company provides a wide range of services for the delivery of goods both within the country and abroad. We specialize in fast and reliable delivery so that your orders arrive on time and in perfect condition.</p>

	<h2 class="faq__second-heading">How can I track my order?</h2>
	<p class="faq__paragraph">
		After sending the order, you will send a unique tracking number (tracking number). Using this number on our site, you will know the current status on your site as well.
	</p>

	<h2 class="faq__second-heading">Do you have express delivery services?</h2>
	<p class="faq__paragraph">
		Yes, we offer express delivery services for those who need immediate delivery of goods.
	</p>

	<h2 class="faq__second-heading">What products do you deliver?</h2>
	<p class="faq__paragraph">
		We deliver a wide range of products including documents, electronics, clothing, food and much more. There are certain restrictions on dangerous or prohibited goods.
	</p>

	<h2 class="faq__second-heading">If the product was damaged during delivery, what should I do?</h2>
	<p class="faq__paragraph">
		If your item was damaged during shipping, please contact our support team as soon as possible. We will promptly resolve the issue of compensation or product replacement.
	</p>

	<h2 class="faq__second-heading">Can I change the delivery address after the order has been shipped?</h2>
	<p class="faq__paragraph">
		Yes, you can change the shipping address by contacting our support team. Please note that the change of address is possible only up to a certain stage of delivery.
	</p>

	<h2 class="faq__second-heading">How can I contact your support?</h2>
	<p class="faq__paragraph">
		Our support service can be found by phone, email or via chat on our website. We are always ready to help you with any questions or problems.
	</p>
</section>

app/views/pages/index.html.erb
<% content_for :title do %>
MAKE DEL
<% end %>

<section class="overlay">
	<div class="overlay__slogan-wrapper">
		<p class="overlay__slogan">Where your needs meet our expertise — MAKE Delivery.</p>
		<p class="overlay__description">
			At MAKE Delivery, we turn logistics into a seamless experience. Our mission is to ensure your goods are delivered efficiently, reliably, and always on time. From local to international shipments, we tailor our services to meet your needs, providing innovative solutions that drive your business forward. With MAKE Delivery, you can trust that your success is our priority.
		</p>
	</div>
</section>

<main class="content">
	<div class="content__image-container">
		<div class="content__image-first-row">

			<%# Check out tracklist %>

			<%= link_to orders_path, class: "content__image-href animated-from-left" do %>
				<%= content_tag :span, class: "content__image-text" do %>
					Check out tracklist
					<%= content_tag :i, "", class: "fa-solid fa-arrow-right" %>
				<% end %>
				<%= content_tag :div, class: "content__image-wrapper" do %>
					<%= image_tag "https://plus.unsplash.com/premium_photo-1661963219843-f1a50a6cfcd3?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8dHJ1Y2tzfGVufDB8fDB8fHww", class: "content__image", alt: "MAKE tracking list" %>
				<% end %>
			<% end %>

			<%# About Us %>

			<%= link_to about_path, class: "content__image-href animated-from-right" do %>
				<%= content_tag :span, class: "content__image-text" do %>
					About Us
					<%= content_tag :i, "", class: "fa-solid fa-arrow-right" %>
				<% end %>
				<%= content_tag :div, class: "content__image-wrapper" do %>
					<%= image_tag "https://img.freepik.com/free-photo/professional-truck-driver-front-long-transportation-vehicle-holding-thumbs-up-ready-new-ride_342744-1343.jpg", class: "content__image", alt: "About us" %>
				<% end %>
			<% end %>

		</div>

		<div class="content__image-second-row">

			<%# FAQ %>

			<%= link_to faq_path, class: "content__image-href animated-from-left" do %>
				<%= content_tag :span, class: "content__image-text" do %>
					FAQ
					<%= content_tag :i, "", class: "fa-solid fa-arrow-right" %>
				<% end %>
				<%= content_tag :div, class: "content__image-wrapper" do %>
					<%= image_tag "https://plus.unsplash.com/premium_photo-1682144324433-ae1ee89a0238?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8dHJ1Y2t8ZW58MHx8MHx8fDA%3D", class: "content__image", alt: "About us" %>
				<% end %>
			<% end %>

			<%# Decisions for business %>

			<%= link_to decisions_for_business_path, class: "content__image-href animated-from-right" do %>
				<%= content_tag :span, class: "content__image-text" do %>
					Decisions for business
					<%= content_tag :i, "", class: "fa-solid fa-arrow-right" %>
				<% end %>
				<%= content_tag :div, class: "content__image-wrapper" do %>
					<%= image_tag "https://media.istockphoto.com/id/169998821/photo/truckers-and-tablet.jpg?s=612x612&w=0&k=20&c=wmJ6PxmMAmaQtYHZqo3vm9n68K99NaDb3f03yLHuTwU=", class: "content__image", alt: "About us" %>
				<% end %>
			<% end %>

		</div>
	</div>
</main>

app/views/pages/profile.html.erb
<% content_for :title do %>
  Profile
<% end %>

<section class="profile">

</section>