config/routes.rb
Rails.application.routes.draw do
  resources :order_requests

  devise_for :users, controllers: { registrations: "users/registrations" }
  root 'pages#index'

  resources :orders
  resources :customers
  resources :drivers
  resources :vehicles
  resources :products

  # pages
  get "/faq", to: "pages#faq"
  get "/about", to: "pages#about"
  get "/decisions_for_business", to: "pages#decisions_for_business"

end

app/models/driver.rb
class Driver < ApplicationRecord
  include PreventDestroyIfOrdersStatusIsInProgress

  validates :name, :surname, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :contact_number, presence: true, uniqueness: true

  belongs_to :vehicle, optional: true
  has_many :orders, dependent: :nullify
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  before_action :set_driver, only: [:show, :edit, :update, :destroy]

  def index
    @drivers = Driver.all
  end

  def new
    @driver = Driver.new
    @available_vehicles = find_available_vehicles
  end

  def edit
    @available_vehicles = find_available_vehicles.to_a
    @available_vehicles = [@driver.vehicle].compact + @available_vehicles if @driver.vehicle
  end

  def create
    @driver = Driver.new(driver_params)
    @available_vehicles = find_available_vehicles

    if @driver.save
      redirect_to drivers_path
    else
      render :new
    end
  end

  def update
    if @driver.update driver_params
      redirect_to drivers_path
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    @driver.destroy
    redirect_to drivers_path
  end

  private

  def driver_params
    params.require(:driver).permit(:name, :surname, :contact_number, :email, :vehicle_id)
  end


  def set_driver
    @driver = Driver.find(params[:id])
  end

  def find_available_vehicles
    Vehicle.left_outer_joins(:driver).where(drivers: { id: nil })
  end
end

app/views/drivers/edit.html.erb
<% content_for :title do %>
  Editing driver info
<% end %>

<section class="entity-table">
  <h1 class="mb-3">Editing <%= @driver.name + " " + @driver.surname %> info </h1>

  <%= form_with model: @driver, url: driver_path do |form| %>
    <div class="table-container">
      <table class="table-bordered">
        <thead>
        <tr>
          <th>Name</th>
          <th>Surname</th>
          <th>Contact Number</th>
          <th>Email</th>
          <th>Vehicle</th>
          <th></th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <td><%= form.text_field :name %></td>
          <td><%= form.text_field :surname %></td>
          <td><%= form.text_field :contact_number %></td>
          <td><%= form.text_field :email %></td>
          <td>
            <%= form.collection_select :vehicle_id, @available_vehicles, :id, :vehicle_identification_number, include_blank: "None" %>
          </td>
          <td>
            <div class="action-container">
              <%= link_to "Back", driver_path(@driver), class: "btn btn-primary back-button" %>
              <%= form.submit "Save", class: "btn btn-success" %>
            </div>
          </td>
        </tr>
        </tbody>
      </table>
    </div>
  <% end %>
</section>

app/views/drivers/index.html.erb
<% content_for :title do %>
  Drivers
<% end %>

<section class="entity-table">
  <h1 class="mb-3">Drivers</h1>
  <%= link_to "Add new driver", new_driver_path, class: "mb-3 btn btn-primary" %>

  <div class="table-container">
    <table class="table-bordered">
      <thead>
      <tr>
        <th>Name</th>
        <th>Surname</th>
        <th>Phone</th>
        <th>Email</th>
        <th>Vehicle</th>
        <th></th>
      </tr>
      </thead>
      <% @drivers.each do |driver| %>
        <tbody>
        <tr>
          <td><%= driver.name %></td>
          <td><%= driver.surname %></td>
          <td><%= driver.contact_number %></td>
          <td><%= driver.email %></td>
          <td>
            <% if driver.vehicle_id.blank? %>
              <%= "None" %>
            <% else %>
              <%= link_to "#{driver.vehicle.brand + " " + driver.vehicle.model}", vehicle_path(driver.vehicle_id), class: "link-opacity-100-hover" %>
            <% end %>
          </td>
          <td>
            <div class="action-container">
              <%= link_to "Show", driver_path(driver), class: "btn btn-primary show-button" %>
              <%= button_to "Delete", driver, method: :delete, class: "btn btn-danger delete-button" %>
            </div>
          </td>
        </tr>
        </tbody>
      <% end %>
    </table>
  </div>
</section>

app/views/drivers/new.html.erb
<% content_for :title do %>
  Add driver
<% end %>

<section class="entity-table">
  <h1 class="mb-3">New driver</h1>
  <%= form_with model: @driver do |form| %>
    <div class="table-container">
      <table class="table-bordered">
        <thead>
        <tr>
          <th>Name</th>
          <th>Surname</th>
          <th>Phone</th>
          <th>Email</th>
          <th>Select free vehicle</th>
          <th></th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <td><%= form.text_field :name %></td>
          <td><%= form.text_field :surname %></td>
          <td><%= form.text_field :contact_number %></td>
          <td><%= form.text_field :email %></td>
          <td>
            <%= form.collection_select :vehicle_id, @available_vehicles, :id, :vehicle_identification_number, prompt: "None" %>
          </td>
          <td>
            <div class="action-container">
              <%= link_to "Back", drivers_path, class: "btn btn-primary back-button" %>
              <%= form.submit "Save", class: "btn btn-success" %>
            </div>
          </td>
        </tr>
        </tbody>
      </table>
    </div>
  <% end %>
</section>

app/views/drivers/show.html.erb
<% content_for :title do %>
  Driver
<% end %>


<section class="entity-table">
  <h1 class="mb-3">Driver <%= @driver.name + " " + @driver.surname %></h1>

  <div class="table-container">
    <table class="table-bordered">
      <thead>
        <tr>
          <th>Name</th>
          <th>Surname</th>
          <th>Phone</th>
          <th>Email</th>
          <th>Vehicle</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @driver.name %></td>
          <td><%= @driver.surname %></td>
          <td><%= @driver.contact_number %></td>
          <td><%= @driver.email %></td>
          <% if @driver.vehicle_id == nil %>
            <td><%= "None" %></td>
          <% else %>
            <td><%= link_to "#{@driver.vehicle.brand + " " + @driver.vehicle.model}", vehicle_path(@driver.vehicle_id), class: "link-opacity-100-hover" %></td>
          <% end %>
          <td>
            <div class="action-container">
              <%= link_to "Back", drivers_path, class: "btn btn-primary back-button" %>
              <%= link_to "Edit", edit_driver_path(@driver), class: "btn btn-primary edit-button" %>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</section>